project_name: g

builds:
   -
    id: main
    binary: g-{{.Os}}-{{ .Arch }}
    main: main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
        - goos: darwin
          goarch: 386
    env:
      - CGO_ENABLED=0
    ldflags:
        - -s -w
    no_unique_dist_dir: true

archives:
  -
    id: main
    builds:
      - main
    name_template: "g_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

gomod:
  proxy: true

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "main_checksums.txt"