baseURL = ''
languageCode = 'en-us'
title = 'g | The teeny-tiny scaffold tool'
theme = 'hugo-whisper-theme'

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "docs/"
    weight = 2

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup]
  [markup.highlight]
    style = 'vim'
    noClasses = false

[params]
  google_analytics_id=""
  homepage_button_link = 'docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = '`g` is a teeny-tiny scaffold tool for creating new projects based on templates. It is written in Go and is cross-platform.'
